--2016-04-12 21:02:03--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 103.245.222.175
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|103.245.222.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1522812 (1.5M) [text/x-python]
Saving to: ‘get-pip.py’

31% [===========>                           ] 482,427     2.80KB/s  eta 6m 3s  34% [============>                          ] 531,579     3.07KB/s  eta 6m 3s  35% [=============>                         ] 547,963     3.16KB/s  eta 5m 1s  37% [=============>                         ] 564,347     3.24KB/s  eta 5m 1s  38% [=============>                         ] 580,731     3.33KB/s  eta 5m 1s  39% [==============>                        ] 597,115     3.42KB/s  eta 5m 1s  39% [==============>                        ] 605,307     3.47KB/s   in 2m 50s 

2016-04-12 21:04:55 (3.47 KB/s) - Connection closed at byte 605307. Retrying.

--2016-04-12 21:04:56--  (try: 2)  https://bootstrap.pypa.io/get-pip.py
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|103.245.222.175|:443... failed: Connection timed out.
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... failed: Name or service not known.
wget: unable to resolve host address ‘bootstrap.pypa.io’
